name: ppsg
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
 - python=3
 - pyqt
 - numpy
 - pandas
 - scipy
 - matplotlib
 - scikit-learn
 - docutils
 - PyYAML=3.12
 - cython
 - plio
 - pyhat
 - qt
 - qtmodern
 - pip
 - pip:
   - Qtickle
